runtime: java17
env: standard

handlers:
  - url: /.*
    script: auto

env_variables:
  DB_NAME: "telegrambot1995"
  CLOUD_SQL_INSTANCE: "telegram-bot-409613:europe-west1:telegrambot1995"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  BOT_TOKEN: "6469305947:AAGLCOICXhhzeCU8t3SI68TPwOjs_prpQIE"
