package car.autoSpotterBot.state.transState;

public enum UserStateInAuto {
    START,
    AUTO,
    IMMOBILE,
    PLACE_AUTOMOBILE_AD,
    PLACE_TRUCK_AD,
    PLACE_AGRO_TECH_AD,
    PLACE_OTHER_TECH_AD,
    PLACE_SPARE_PARTS_AD,
    AUTO_AD_PLACED,
    TRUCK_AD_PLACED,
    AGRO_TECH_AD_PLACED,
    SPARE_TECH_AD_PLACED,
    OTHER_TECH_AD_PLACED,
    GETTING_ADS,
    AUTO_AD_CANCELLED,
    WAITING_FOR_CONFIRMATION,
    SEARCH_AD_AUTO,
    ADD_TO_AUTO_FAVORITE,
    ADD_TO_IMMO_FAVORITE,
    SEND_PHOTO_AUTO,
    SEND_PHOTO_TRUCK,
    SEND_PHOTO_AGROTECH,
    SEND_PHOTO_OTHER_TECH,
    SEND_PHOTO_SPARE_PARTS,
    AUTO_SECTION, TRUCK_SECTION, AGRO_TECH_SECTION, OTHER_TRANS_SECTION, SPARE_PARTS_SECTION, DEFAULT,
    EDIT_MY_AD_TEXT

    // ... und so weiter für jeden Schritt
}
